### ISSUE TITLE
Retornando somente o primeiro Evento

### ISSUE THREAD

**Issue by peteraf** [PostmonAPI/correios.postmon.com.br#9]
Esta retornando somente o primeiro evento.

Link de exemplo
https://correios.postmon.com.br/webservice/buscaEventos/?objetos=PL499734076BR

**Comment by iurisilvio** [comment]
Essa é uma limitação do serviço dos Correios. Eles retornam todos os eventos apenas se você tiver um usuário/senha diferente do padrão.

Caso você tenha, você pode passar essa autenticação nos headers `x-correios-usuario` e `x-correios-senha`.

https://github.com/PostmonAPI/correios.postmon.com.br/blob/98d58e8d7f0dd985b882fa9bed88f6d5f84e7014/postmon_correios/correios.py#L40-L41

**Comment by iget-esoares** [comment]
Sugiro colocar isso no readme :-)
